# Generated by Django 2.1.5 on 2019-02-08 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Services.ProjectSkill'),
        ),
    ]
