# Generated by Django 2.1.5 on 2019-02-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_project_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
