# Generated by Django 2.0.7 on 2019-02-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_auto_20190208_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
